### ISSUE TITLE
May be LibreLogin not compatible with ViaVersion

### ISSUE THREAD

**Issue by naipret** [kyngs/LibreLogin#363]
[Leaf](https://github.com/Winds-Studio/Leaf) is a paper folk that focuses on performance and optimizations

![Image](https://github.com/user-attachments/assets/ef552462-905a-4b1c-b656-8e61a36495c9)
- The 1st server is using another login plugin (can login normally)
- The 2nd server is currently using LibreLogin (can't connect to the server)
  ![Image](https://github.com/user-attachments/assets/966a0baf-20a9-4ddf-a22e-1f272844c110)

Both server use the same plugin (but different login plugin), setup and leaf version:
- Plugin list:
  ```
  [16:02:02 INFO]: ℹ Server Plugins (32):
  [16:02:02 INFO]: Paper Plugins (1):
  [16:02:02 INFO]:  - LibreLogin
  [16:02:02 INFO]: Bukkit Plugins (31):
  [16:02:02 INFO]:  - AnarchyExploitFixes, BetterTeams, Chunky, ChunkyBorder, CMI, CMILib, DiscordSRV, EndCrystalNerf, EntityDetection, FastAsyncWorldEdit
  [16:02:02 INFO]:  GravesX, Jobs, LuckPerms, Maintenance, packetevents, PlaceholderAPI, ProtocolLib, Quests, Residence, SelectionVisualizer
  [16:02:02 INFO]:  Skript, TimeBar, TimePauser, TradeSystem, TreeFeller, TryMe, VeinMiner, ViaBackwards, ViaVersion, voicechat
  [16:02:02 INFO]:  voicechat-discord
  ```
- Leaf version:
  ```
  [16:07:06 INFO]: This server is running Leaf version 1.21.4-495-ver/1.21.4@91a911a (2025-06-18T17:14:16Z) (Implementing API version 1.21.4-R0.1-SNAPSHOT)
  ```

**Comment by greaternot** [comment]
i really think it has something to do with the limbo server, its not a problem with leafmc. But, actually a problem with viaversion plugins

would you really mind letting me know about the alternative plugin that you are using? i really want to setup viaversion on my server but librelogin makes it impossible to do so.. i'll really appreciate you if you let me know❤

**Comment by naipret** [comment]
> i really think it has something to do with the limbo server, its not a problem with leafmc. But, actually a problem with viaversion plugins
> 
> would you really mind letting me know about the alternative plugin that you are using? i really want to setup viaversion on my server but librelogin makes it impossible to do so.. i'll really appreciate you if you let me know❤

I'm currently using nLogin as an alternative to LibreLogin, and it works normally with ViaVersion
Let me know if you have any other questions

**Comment by naipret** [comment]
> i really think it has something to do with the limbo server, its not a problem with leafmc. But, actually a problem with viaversion plugins
> 
> would you really mind letting me know about the alternative plugin that you are using? i really want to setup viaversion on my server but librelogin makes it impossible to do so.. i'll really appreciate you if you let me know❤

Thanks for the info! I actually removed ViaVersion and tried again, and it worked perfectly
So it seems there was an incompatibility issue with ViaVersion

**Comment by sphynxinc** [comment]
I have the same issue with LibreLogin. I hope it will be fixed soon. But with ViaVersion I can't event ping the server.

**Comment by trassert** [comment]
Same problem.

**Comment by Navio1430** [comment]
I've fixed the issue with ViaVersion (which you're probably referring to). Now the plugin is compatible with 1.21.8 paper/velocity 

You can download the latest release (WITHOUT BUNGEECORD SUPPORT!) from here:
https://github.com/Navio1430/LibreLoginProd

You can also build it yourself (I suggest building it at a point where the latest commit matches the latest release).

**Comment by naipret** [comment]
> I've fixed the issue with ViaVersion (which you're probably referring to). Now the plugin is compatible with 1.21.8 paper/velocity
> 
> You can download the latest release (WITHOUT BUNGEECORD SUPPORT!) from here: https://github.com/Navio1430/LibreLoginProd
> 
> You can also build it yourself (I suggest building it at a point where the latest commit matches the latest release).

Thanks 😘

**Comment by GitBarna** [comment]
another thing @Navio1430 
the modrinth version is not updated, can you update that as well
(Bc when I tried to use that verison it still had the same issue)

**Comment by Navio1430** [comment]
Done. Btw, many errors often occur because of plugin conflicts.

**Comment by kyngs** [comment]
@naipret Can you confirm whether this is still a problem on the latest dev build?
Should be fixed.

**Comment by naipret** [comment]
I tested the latest dev build with this setup:
- Paper 1.21.11
- LibreLogin 0.25.0-SNAPSHOT 39397c47585e193d71cc84d3043f4a61df725124
- Viaversion + Viabackwards 5.12.0
- Client: 1.20.6, 1.21.11, 26.2.1

And it works exactly as expected
Thanks

**Comment by naipret** [comment]
However, I am encountering the same issue as #411
Even with `remember-last-server=true`, I still get sent to the world's default spawn point, despite a respawn point or new last spawn location having been saved
In my case, I am using the firstjoin plugin
